features/step_definitions/input.steps.js

Fixed E2E button selector

---

src/components/ProviderLogin/ProviderLogin.less
src/index.less

* Fixed SVG size for rotating circle
* Fixed toast styles (override CSS-in-JS properties by `!important`)

Fixed style issues

---

src/components/Card/Card.container.ts
src/components/Card/Card.less
src/components/Card/Card.spec.tsx
src/components/Card/Card.tsx
src/components/Checkbox/Checkbox.less
src/components/Checkbox/Checkbox.spec.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
src/components/Checkbox/index.ts
src/components/Modal/variant/SettingsModal.less
src/components/Modal/variant/SettingsModal.tsx
src/routes/Board/Board.container.tsx
src/routes/Board/Board.spec.tsx
src/routes/Board/Board.tsx
src/routes/NewBoard/NewBoard.container.tsx
src/types/index.ts

Toggle show card author

---

database.rules.json
src/routes/BoardGuard/BoardGuard.spec.tsx
src/routes/BoardGuard/BoardGuard.tsx

Check for invalid board reference on join

---

src/components/UserList/UserList.tsx

Reduced nr of shown users

---

src/routes/Board/Board.less
src/routes/Board/Board.tsx

Removed scale animation on PhaseSplash appearance

---

src/components/Avatar/Avatar.tsx
src/components/Card/Card.tsx
src/util/emojis.spec.ts
src/util/emojis.ts

Omits the leading emoji from the username next to the Avatar on Cards

Cards: ( 🦄 ) 🦄 Fan -> ( 🦄 )  Fan

---

.eslintrc.js
.github/workflows/dev.yml
.github/workflows/staging.yml
.prettierrc.json
src/components/AdvancedBoardSetup.tsx
src/components/Card.tsx
src/components/Column.tsx
src/components/TemplateCard.tsx
src/domain/auth.ts
src/domain/board.ts
src/index.tsx
src/locale/index.ts
src/react-app-env.d.ts
src/routing/Router.tsx
src/routing/pages/Board.tsx
src/routing/pages/BoardContext.ts
src/routing/pages/Homepage.tsx
src/routing/pages/SignIn.tsx
src/routing/pages/Templates.tsx
src/routing/util/ProtectedRoute.tsx
src/routing/util/SessionCheck.tsx
src/routing/util/useBoardGuard.ts
src/serviceWorker.ts
src/setupTests.ts
src/style/theme.ts
src/types/state.ts
src/util/toBoolean.test.ts
src/util/toBoolean.ts
src/util/usernameGenerator.ts
src/util/withId.ts

Fixes current eslint failures

---

src/components/Header/Header.container.ts
src/components/Header/Header.spec.tsx
src/components/Header/Header.tsx
src/components/UserMenu/UserMenu.spec.tsx
src/components/UserMenu/UserMenu.tsx

The download of the board was made available in all three phases. For this purpose, the download condition has been removed. All variables that were no longer required were also deleted.

Download enabled in all phases

---

src/components/Column/Column.scss
src/components/NoteInput/NoteInput.scss

Originally, I thought you had to include the font into the project. Apparently it works without that too. Please test this.

Add font Raleway

---

package.json
server/package.json
server/yarn.lock
src/components/LoadingIndicator/LoadingIndicator.tsx
src/components/LoadingScreen/LoadingScreen.tsx
src/routes/Board/Board.tsx
src/routes/Board/BoardGuard.tsx
src/routes/PrivateRoute.tsx
src/routes/Router.tsx
src/store/reducer/board.ts
src/utils/authentication/AuthenticationManager.ts
tsconfig.json
yarn.lock

Especially React 16 -> 17 and typescript version bump

Major upgrade of dependencies

---

src/components/MenuBars/MenuBars.scss
src/components/MenuBars/MenuItem/MenuItem.scss
src/constants/style.scss

- `z-index` set above notes
- Added `:hover` animation for menu bar on small desktop size

Fix for minor menu issues

---

README.md
server/README.md
server/docker-compose.yml
server/package.json
server/yarn.lock

`nodemon` will reload the server once the code is changed. This makes development a bit faster as the server will be restarted automatically when it runs with `yarn serve`

Added nodemon to server

---

src/components/BoardUsers/BoardUsers.tsx
src/components/MenuBars/MenuBars.tsx
src/components/Note/Note.tsx
src/routes/Board/Board.tsx
src/routes/Board/BoardGuard.tsx
src/store/index.ts
src/types/store.ts

Instead of importing `useSelector` and `ApplicationState` it's easier to use typed useSelector

Small improvement for Redux

---

src/components/Note/Note.scss
src/components/Note/Note.tsx
src/components/Note/__tests__/__snapshots__/Note.test.tsx.snap
src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteFooter.tsx
src/components/Votes/VoteButtons/AddVoteButton.scss
src/components/Votes/VoteButtons/RemoveVoteButton.scss
src/components/Votes/VoteButtons/VoteButton.scss
src/components/Votes/Votes.scss

Fixes issue where vote count has a large margin to the right side

Alignment of vote buttons 

---

src/components/MenuBars/MenuBars.scss
src/components/MenuBars/MenuItem/DropdownToggleButton.scss
src/components/MenuBars/MenuItem/MenuItem.scss
src/components/Timer/Timer.scss
src/constants/style.scss

Closes #969 (checkout for more details).
This is just a suggestion and a quick and almost clean fix, it's not perfect. 
Perfect would be a rewrite of parts of the css but it's rather complicated.

Fixed menu bars visibility for small screens

---

src/components/JoinRequest/JoinRequest.scss

Fixed issue with colored corners.
Issue: Close #992

Fix issue with colored corners

---

server/src/cloud.ts
server/src/cloud/board.ts
server/src/cloud/userOnlineStatus.ts
server/src/index.ts

Fixed user online status

---

src/components/Badge/Badge.scss
src/components/Badge/Badge.tsx
src/components/Badge/index.ts
src/components/BoardHeader/ParticipantsList/Participant.tsx
src/components/BoardHeader/ParticipantsList/__tests__/ParticipantsList.test.tsx

Add badge (or in the future a coin/chip) to each participant.
- Create `Badge.tsx` and corresponding scss file
- Update `ParticipantsList.test.tsx`

Closes #1042: Badge

---

src/components/MenuBars/MenuBars.tsx
src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap

Set href in `onClick` function.
Closes #1094 
- Remove `Link` component

Closes #1094: Missing icon in menu bar

---

src/routes/Board/Board.tsx

Seems like chrome needs an additional undefined check. Code works before on Firefox without issues.
Closes #1086 
- Add additional undefined check

Closes #1086: Undefined getTime

---

src/components/Board/Board.scss

Fix board navigation opacity

---

src/components/MenuBars/MenuItem/DropdownToggleButton.scss

Closes #1106 
Remove jumping label text.
https://user-images.githubusercontent.com/60005702/143860163-5217443b-05d4-48f5-ac05-73aa8f672312.mov

Closes #1106: Remove jumping text

---

src/components/Board/Board.scss
src/components/MenuBars/MenuBars.tsx
src/components/MenuBars/MenuItem/variants/VoteConfigurationButton.tsx
src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap

Tabindex did not work as expected.
- Update `tabIndex` value
https://user-images.githubusercontent.com/60005702/143861711-d01386e6-0f2d-4b54-834d-d5af571971b6.mov

Update tabindex for Voting

---

src/components/Infobar/Infobar.scss
src/constants/style.scss

Closes #1148: Update z-index

---

.github/workflows/cleanup.yml
.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml

fix actions, cant use env in jobs.if and use quotes around if statement( needed for colon in string)

fix actions

---

src/components/Note/Note.tsx
src/components/Note/__tests__/Note.test.tsx
src/components/NoteDialog/NoteDialog.tsx
src/components/NoteDialog/NoteDialogComponents/NoteDialogNote.tsx
src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteFooter.tsx
src/components/NoteDialog/__tests__/NoteDialog.test.tsx
src/components/Votes/VoteButtons/AddVoteButton.tsx
src/components/Votes/Votes.tsx
src/routes/Board/Board.tsx

Closes #1145: Disable button if all votes are used

---

src/components/BoardHeader/ParticipantsList/ParticipantsList.tsx

Closes #1134: Reset search string

---

src/routes/Homepage/Homepage.scss

Changed font properties for hero teaser on homepage

---

src/components/Board/Board.scss

Fixed colors for board spacer in light mode

---

src/assets/icon-arrow-right.svg
src/routes/Homepage/Homepage.scss
src/routes/Homepage/Homepage.tsx

Added arrow right icon to start button on homepage

---

src/components/DotButton/DotButton.scss
src/components/Note/Note.scss
src/components/Votes/VoteButtons/RemoveVoteButton.scss

Closes #1133: Increase animation speed

---

src/store/middleware/__tests__/users.test.ts
src/store/middleware/board.ts
src/store/middleware/users.ts

Add hurry-up notification for last unready user

---

src/store/reducer/__tests__/note.test.ts
src/store/reducer/note.ts

Closes #1120: Missing cards as moderator

---

src/components/Badge/Badge.scss
src/components/BoardHeader/ParticipantsList/Participant.tsx
src/components/BoardUsers/UserAvatar.tsx

Fix badge position for `<UserAvatar />`

---

src/index.scss
src/routes/Homepage/Homepage.scss

Fix background color and illustration overlap

---

src/components/Votes/VoteButtons/AddVoteButton.scss

Increased contrast of add `<AddVoteButton />`

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/Infobar/__tests__/__snapshots__/Infobar.test.tsx.snap
src/components/Votes/VoteDisplay/VoteDisplay.scss
src/components/Votes/VoteDisplay/VoteDisplay.tsx

Add remaining vote tooltip as `title=` attribute

---

src/routes/Board/Board.tsx

Sort notes by votes of completed iterations

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/DotButton/DotButton.tsx
src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogDeleteNoteButton.tsx
src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogUnstackNoteButton.tsx
src/components/NoteDialog/__tests__/__snapshots__/NoteDialog.test.tsx.snap

Add tooltip titles to `<NoteDialog />` buttons

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/Badge/Badge.scss
src/components/BoardHeader/ParticipantsList/__tests__/ParticipantsList.test.tsx
src/components/MenuBars/MenuItem/variants/VoteConfigurationButton.tsx
src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap
src/components/Toggle/Toggle.scss
src/components/Toggle/Toggle.tsx
src/components/Toggle/index.ts
src/components/ToggleButton/ToggleButton.scss
src/components/ToggleButton/ToggleButton.tsx
src/components/ToggleButton/__tests__/__snapshots__/ToggleButton.test.tsx.snap
src/constants/style.scss

Replaced yes/no toggle with toggle button

---

src/components/MenuBars/MenuItem/MenuButton.tsx
src/components/MenuBars/MenuItem/MenuItem.scss

Hide menu bar tooltip on focus (and show only on hover)

---

src/store/middleware/board.ts

Closes #1196: Online/Offline works now as expected

---

src/store/middleware/board.ts

Remove console logs

---

server/src/cloud/note.ts
src/components/Column/Column.tsx
src/components/NoteInput/NoteInput.tsx
src/components/NoteInput/__tests__/NoteInput.test.tsx

Closes #1205 
- Restrict messages to length of `1024` chars
- Limit: 5 chars
https://user-images.githubusercontent.com/60005702/144823197-44e01ad2-f3b8-40ee-a4e4-222006078af8.mov

Closes #1205: Note text length

---

src/components/MenuBars/MenuItem/DropdownToggleButton.tsx
src/components/MenuBars/MenuItem/MenuItem.scss
src/components/MenuBars/MenuItem/variants/TimerToggleButton.tsx
src/components/MenuBars/MenuItem/variants/VoteConfigurationButton.tsx

Closes #1206 
https://user-images.githubusercontent.com/60005702/144838762-469e7c4a-f7c2-489d-bc6f-01735f1e7bb2.mov

Closes #1206: Active toggle state

---

src/components/Column/Column.scss
src/components/NoteInput/NoteInput.scss

Aligned edit icon with note input icon.
- Changed note-input to flexbox
- Aligned edit icon with note-input icon using margin
- Aligned header text with note-input text

Align edit icon with note input icon

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/Board/Board.tsx
src/components/Column/Column.scss
src/components/Column/Column.tsx
src/routes/Board/Board.tsx

Highlights the board border when user is moderating.
Visual Changes

Highlight moderation

---

server/src/go.mod
server/src/go.sum
server/src/main.go

* Changed callback host to single CLI or environment variable parameter
* Updated goth library and removed replacement for PR on `cdreier`s repo

Changed callback host to single CLI parameter

---

server/src/database/users.go

We had the problem that every time a third party login with the same account, a new user was created. This is problematic because it means that the user id changes on every login. 
Looking at our query, new users shouldn't have been created on each login because the WHERE clause forbids it. But that didn't work. 
```go
createNewUser := d.db.NewInsert().
Model((*User)(nil)).
ColumnExpr("name, account_type").
TableExpr(fmt.Sprintf("(SELECT ? as name, '%s'::account_type as account_type) as sub_query", accountType), name).
Where("(SELECT NOT user_exists FROM exists_check)").
Returning("id")
```
But what was actually executed looks different because for some reason the WHERE is missing:
```sql
"create_new_user" AS (INSERT INTO "users" (name, account_type) SELECT name, account_type FROM (SELECT …
```

Fix third party login 

---

server/src/go.mod
server/src/go.sum

Resolves https://github.com/inovex/scrumlr.io/security/dependabot/108

Update github.com/opencontainers/runc to v1.1.2

---

src/components/Note/Note.tsx
src/components/NoteDialog/NoteDialog.tsx
src/components/SettingsDialog/Participants/Participants.tsx

Avatar wasn't updated in ParticipantsSettings and NoteDialog. Added the missing props to update the avatar correctly. 
Closes #1903 
- Added missing avatar prop of NoteDialog
- Added missing avatar prop of Participants
There are visual changes, but it's just updating the avatar, so please refer the the issue for before screenshots.

Bugfix: Update avatar in components

---

server/src/api/boards.go

Closes #1887 
- Filter both columns and notes to exclude hidden ones from the export

Remove hidden columns and notes from the exports

---

package.json
public/index.html
src/index.scss
src/index.tsx
src/routes/LoginBoard/LoginBoard.tsx
yarn.lock

* Replaced usage of inovex CDN by integrating "Raleway" directly into project (@fontsource)
* Toggle display of cookie notice by `SCRUMLR_SHOW_LEGAL_DOCUMENTS`
* Toggle display of "Accept terms" on login by `SCRUMLR_SHOW_LEGAL_DOCUMENTS`

Integrated font-family and enhanced toggling of legal documents

---

public/locales/de/translation.json
public/locales/en/translation.json
src/assets/icon-globe.svg
src/assets/icon-key.svg
src/components/BoardHeader/BoardHeader.scss
src/components/BoardHeader/BoardHeader.tsx
src/components/BoardHeader/__tests__/BoardHeader.test.tsx

Closes #1942 
- Added globe and key icon svg
- Changed translations

Change title and icon of the board header mode

---

src/components/Note/Note.scss
src/components/Note/Note.tsx
src/constants/style.scss

Added user avatar chip

---

src/components/Column/Column.scss

Fixed column header overflow

---

src/components/CookieNotice/CookieNotice.tsx
src/components/TimerDialog/TimerDialog.tsx
src/components/VotingDialog/VotingDialog.tsx
src/constants/storage.ts
src/i18n.ts
src/index.tsx
src/utils/storage.ts

Save custom timer/voting setting

---

src/components/MenuBars/MenuBars.scss
src/components/MenuBars/MenuItem/MenuItem.scss
src/components/SettingsDialog/Components/AvatarSettings.scss
src/components/SettingsDialog/ProfileSettings/ProfileSettings.scss
src/components/SettingsDialog/ProfileSettings/ProfileSettings.tsx

Just two CSS bugfixes.
- Fix division in CSS files, by using calc() (webpack doesn't allow division without the function call)
- Fix the scrollbar on the profile settings
Before:
After:

Small CSS Fixes

---

README.md

- added @Schwehn42 to the list of team members. (resolves #2078)
- README.md – add avatar

add @schwehn42 to contributors

---

src/components/BoardHeader/ParticipantsList/ParticipantsList.scss
src/components/BoardHeader/ParticipantsList/ParticipantsList.tsx

Clicking on the participantList doesn't close it.
Before: 
https://user-images.githubusercontent.com/44020029/191933770-b240e0a0-f256-4147-bcc3-6322bb7d3066.mov
After:
https://user-images.githubusercontent.com/44020029/191933916-76653e05-c8a0-4f59-a693-26dc95369561.mov

Fix participantsList

---

public/locales/en/translation.json

changed the translation for Notes from 'Kärtchen' to 'Notes' in en

Fix a wrong translation

---

src/components/VotingDialog/VotingDialog.tsx

The vote limit has been 0. But for obvious reasons, a vote limit of 0 doesn't make any sense. That's why I've changed it to a minimum of 1 vote.

Fix vote limit

---

src/components/MenuBars/MenuBars.tsx
src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap

Active state for timer & voting button

---

src/components/Column/Column.tsx

Add  `onDoubleClick` event handler to column title element for easy access editing

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/Infobar/Infobar.scss
src/components/Infobar/Infobar.tsx
src/components/Infobar/__tests__/Infobar.test.tsx
src/components/MenuBars/MenuBars.tsx
src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap

Rename `focus mode` to `presenter mode`

---

src/components/Infobar/Infobar.scss
src/components/Timer/Timer.scss
src/routes/StackView/StackView.tsx
src/store/middleware/board.tsx
yarn.lock

Fixed a few bugs regarding the stack view navigation and moderation of notes:
- Notes in hidden columns will not be shared with other users
- Normal participants can't navigate to hidden columns anymore (hidden columns in between visible columns will simply be skipped)
- Fixed Stack View layout bugs for Safari

Stack View and Moderation Bugfixes

---

src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteContent.tsx
src/components/StackNavigation/StackNavigation.tsx
src/store/action/note.ts
src/store/reducer/view.ts
src/types/view.ts
src/utils/test/getTestApplicationState.ts

Fixed edit note in stack view in combination with arrow hotkeys

---

src/components/BoardHeader/BoardHeader.scss
src/components/BoardHeader/BoardHeader.tsx
src/components/ShareButton/ShareButton.scss
src/components/ShareButton/ShareButton.tsx
src/components/ShareButton/index.ts

I've moved the share button to it's own component and added `aria-label` for accessibility & `title` for the tooltip on hover

improvement: add aria-label and title to share button

---

src/components/Timer/Timer.tsx

Show readiness reset toast only if some users are ready

---

src/components/Column/Column.scss

Change end to flex-end

---

Dockerfile
README.md
package.json
server/README.md
server/docker-compose.yml
server/src/api/login.go
server/src/auth/auth.go
server/src/common/http.go
server/src/common/http_test.go
server/src/database/migrations/sql/5_add_key_rotation.down.sql
server/src/database/migrations/sql/5_add_key_rotation.up.sql
server/src/database/users.go
server/src/main.go

* Updated default port of frontend application (previously `:80 `now set to `:8080`)
* Added option to rotate keys
* Added `--insecure` parameter to add extra caution for default startups

Bundle of breaking changes

---

src/components/SettingsDialog/Feedback/Feedback.scss

The hover & checked effect of the feedback options have been changed to match the effects of the participants' list
Closes #2739 
- Changed the hover effect of feedback options
- Changed the checked effect of feedback options 

improvement: change checked effect of feedback options

---

src/components/Votes/Votes.scss
src/components/Votes/Votes.tsx

- Replace deprecated `VFC` with `FC`
- Decrease gap from 12px (with padding) to 6px

fix: decrease gap between voting buttons

---

.github/workflows/continuous-integration.yml
.github/workflows/package.yml
Dockerfile

- Bumped multiple Actions to remove deprecation warnings
- Bumped `Node.js` version to `lts-hydrogen`

fix: Bump Action dependencies

---

.github/workflows/deploy_to_dev_cluster.yml

fixed wrong deploy message

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy_to_dev_cluster.yml
k8s/deployment.yaml

Draft: hotfix branch name too long

---

src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteFooter.scss

I accidentally deleted a line in the styling which missaligned the avatar.
- Add back line to realign the avatar
Before:
After:

fix: stack view author avatar  

---

.github/workflows/continuous-integration.yml

chore: update_octomind_to_v2

---

README.md

Added @MarvinRoth, @blxckOxymoron, and @Quasilius-Starlord to the contributors list in the README. Thank you guys! ❤️

New Contributors

---

src/components/SettingsDialog/Feedback/Feedback.tsx
src/components/SettingsDialog/Feedback/__tests__/__snapshots__/Feedback.test.tsx.snap

Changed placeholder mail for feedback form

Replaced mail@inovex.de by stan@scrumlr.io

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy_to_dev_cluster.yml

feat: deploy main branch

---

public/locales/en/translation.json
src/components/TimerDialog/__tests__/__snapshots__/TimerDialog.test.tsx.snap

This commit fixes the timer dialog buttons text to show the plural instead of minute
Closes #3697

fix: plural timer text

---

.github/workflows/deploy_to_dev_cluster.yml

- added `force` to k8s-apply
- fixed `comment-pull-request` running on merge events

fix: minor action fixes

---

public/locales/de/translation.json
public/locales/en/translation.json
src/components/HotkeyAnchor/HotkeyAnchor.tsx

fix #3719
Make required changes in custom timer alert message .and also add changes in both English and German.
go to 
src -> components -> HotkeyAnchor -> HotkeyAnchor.tsx 
inside startTimer function, I just change the title according to the requirement.
and now add changes in both the languages . it's working fine now.

fix: Make required changes in hotkey custom timer message.

---

server/api.postman_collection.json
server/src/api/boards.go
server/src/api/router.go
server/src/services/boards/boards.go
server/src/services/services.go
src/api/board.ts

The timer pill should soon have a button to increment the ongoing timer by one minute. Therefore, I've implemented the backend changes required for that.

feature: increment timer by one minute

---

server/src/api/boards.go
src/api/participant.ts

Change of http status codes when sending a join request with an incorrect passphrase to a protected board for better differentiation during error evaluation.
Closes #3920 
In 'api/boards.go': add check for empty passphrase and change of status code from ForbiddenRequest to BadRequest 
In 'api/participant.ts': Added status codes to the return value when a 400 request is received when trying to join a board

fix: change http response of passphrase request

---

server/api.postman_collection.json
server/src/api/router.go

Add Check to only let users with correct permissions use the /boards/{id} route
In 'api/route.go': Added an check to make sure only users with correct permissions can start/stop/increment the timer

fix: Add  User premission check to /boards/{id} API call

---

.gitignore

- Delete server build from pushed files and add it to gitignore

chore: add `server/src/server` to .gitignore and delete file

---

package.json
server/src/api/context.go
server/src/api/notes.go
server/src/api/notes_test.go
server/src/api/router.go

Changed router.go that check if the user has sufficient rights for this request.
Change to notes_test.go so that the boardID is not sent via the context
In 'context.go' removed unnecessary check when boardID is sent via context, removed checks which are already covered by AuthContext
In 'notes_test.go' sending boardID now as url parameter
In 'router.go' added middelware calls to check user premissions

fix: Check user permission when board is locked

---

.github/workflows/postman_e2e_test.yml
k8s/deployment.yaml

hotfix: dev deployment bug

---

server/src/services/users/users.go

The login method for github users used the google login method. -> Changed this to use the github login method
`services/users/user.go`
changed called method to `CreateGitHubUser`

fix: change github login method from google to github

---

.github/workflows/continuous-integration.yml

hotfix: wrong branch reference

---

src/components/Board/Board.scss
src/components/Column/Column.scss

Switches up the column colors in dark mode which were changed with https://github.com/inovex/scrumlr.io/pull/4283/commits/b680c8eb2f7973a45ce012da5d6005e891dee43c.

fix: switch up dark column colors

---

k8s/deployment.yaml

Bumps dev cluster Postgres to 16.3

chore: update PostgreSQL image to version 16.3

---

.github/actions/deployment_health_check/action.yml

Yesterday, we experienced a very long CI run that was stuck in the "dev cluster health check". This was due to the fact that `curl` could connect to the server itself but did not get a response back – resulting in a pending request, which times out in around 3-4 minutes by default.
To prevent this behavior, since the request for a health check itself should not take longer than a couple of seconds (even this would be ridiculous) we now introduce a hard limit of 10 seconds per request.
The wait time between requests is untouched by this.
- added `--max-time` flag to curl command in ci health check

ci: added timeout to healthcheck request

---

README.md

- I added myself as a contributor 
- Changed the README.md

docs: add new contributor

---

.github/workflows/continuous-integration.yml
.github/workflows/package.yml

Bumps a couple dependencies.
Introduces ARM images on release.

chore: arm64 images on release & action dependency upgrades

---

server/src/database/boards_test.go
server/src/database/testdata/fixture.yml

Additional tests for the board description feature
- extended `fixture.yml` file
- added go tests in `/database/boards_test.go`

test: added boardDescription to go tests and fixture file

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy_to_dev_cluster.yml
.github/workflows/package.yml

Bumps some deps for our CI. Additionally, since GitHub will deprecate its former `set-output` syntax, the new syntax is used now.
- bump deps in `package.yml` and `deploy_to_dev_cluster.yml`
- changed to new output syntax in `ci.yml`

ci: updated actions; adapted to new output syntax

---

package.json
src/index.tsx
yarn.lock

Trying out Microsoft Clarity since it's free and GDPR & CCPA ready

feat: add analytics with microsoft clarity

---

src/store/features/notes/reducer.ts

When ending a voting the user expects to get its note sorted by votes from high to low
``notes/reducer.ts``
- added a case that checks if the `updateVoting` event has been called and updates the note state

add case to note reducer when voting gets updated

---

.github/workflows/sonarqube.yaml
sonar-project.properties

feat: SonarQube

---

.github/workflows/sonarqube.yaml
sonar-project.properties

feat: sonar quality gate

---

sonar-project.properties

hotfix: exclude go test files

---

.github/workflows/continuous-integration.yml

hotfix: skip code scanning on dependabot

---

server/src/api/feedback.go
server/src/api/router.go
server/src/feedback/api.go
server/src/feedback/dto.go
server/src/feedback/service.go
server/src/feedback/service_test.go
server/src/initialize/service.go
server/src/main.go
server/src/services/services.go

Add a feedback package to the scrumlr backend
- Add feedback package
- Add tests for the feedback service

refactor: Add feedback package

---

server/src/api/feedback.go
server/src/api/reactions.go
server/src/database/database.go
server/src/database/reactions_test.go
server/src/feedback/dto.go
server/src/feedback/service_test.go
server/src/feedback/type.go
server/src/reactions/api.go
server/src/reactions/database.go
server/src/reactions/database_dto.go
server/src/reactions/dto.go
server/src/reactions/mock_ReactionDatabase.go
server/src/reactions/mock_ReactionService.go
server/src/reactions/service.go
server/src/reactions/service_test.go
server/src/reactions/type.go

Fix some naming for the already refactored packages.
- Fix naming of reactions package
- Fix naming of feedback package

fix: naming of refactored packages

---

server/src/api/votes.go
server/src/api/votings.go
server/src/database/boards.go
server/src/database/votings_test.go
server/src/voting/api.go
server/src/voting/database.go
server/src/voting/mock_VotingDatabase.go
server/src/voting/mock_VotingService.go
server/src/voting/service.go
server/src/voting/service_test.go

missed things for decupling votes

---

server/src/initialize/service.go
server/src/main.go

Add a service initializer to reduce the call list
- Add new service initializer struct
- Add methods to the service initializer struct

feat: service initializer

---

server/src/.mockery.yaml
server/src/boards/database.go
server/src/boardtemplates/database_dto.go
server/src/boardtemplates/dto.go
server/src/boardtemplates/service_test.go
server/src/columns/database.go
server/src/database/reactions_test.go
server/src/notes/database.go
server/src/votings/database.go

Fix minor issues

---

server/src/notes/database.go
server/src/notes/database_dto.go

Fix note database tests

---

server/src/api/boards_listen_on_board.go
server/src/notes/api.go
server/src/notes/services.go

Move notes update from event filter to note service

---

src/components/SettingsDialog/ExportBoard/__tests__/__snapshots__/ExportBoard.test.tsx.snap
src/i18n/de/translation.json
src/i18n/en/translation.json

minor localization change, fixes #5098 
- change localization as defined

localization: open print view => export pdf

---

server/src/api/event_filter.go
server/src/api/event_filter_test.go
server/src/votings/dto.go
server/src/votings/helpers.go
server/src/votings/helpers_test.go

Fix: update voting

---

.github/workflows/clean_packages.yml

Disables the worflow for removing old packages

Disable clean packages workflow

---

.github/workflows/rebuild_images.yaml

Add manual workflow to rebuild images

Add workflow to rebuild images

---

.github/workflows/continuous-integration.yml

Fix the linter in the golang pipeline
- Update to min golang version 1.23
- Update golang linter to 1.64

fix: golang pipeline

---

src/routes/Boards/Boards.scss
src/routes/Boards/Boards.tsx

hid the toggle which is unused right now #5184 (will be activated after next release)
hid the toggle which is unused right now #5184 (will be activated after next release)

hid the toggle which is unused right now #5184 

---

src/components/SettingsDialog/SettingsDialog.scss
src/components/SettingsDialog/SettingsDialog.tsx
src/components/SettingsDialog/__tests__/SettingsDialog.test.tsx
src/components/SettingsDialog/__tests__/__snapshots__/SettingsDialog.test.tsx.snap
src/i18n/de/translation.json
src/i18n/en/translation.json

Added Logout button in settings dialog
Added Logout button in settings dialog with redirects the user to the login page afterwards and removes it from the store

feat: logout button

---

src/i18n/de/translation.json
src/i18n/en/translation.json
src/routes/Boards/TemplateEditor/TemplateEditor.scss
src/routes/Boards/TemplateEditor/TemplateEditor.tsx
src/routes/Boards/TemplateEditor/__tests__/__snapshots__/TemplateEditor.test.tsx.snap

Kinda forgot we also need that
- add info icon/text between columns editor and buttons

feat: template editor info

---

server/src/votings/database.go
server/src/votings/database_test.go
server/src/votings/mock_VotingDatabase.go
server/src/votings/service.go
server/src/votings/service_integration_test.go
server/src/votings/service_test.go

Add integration tests for voting service and add more unit tests for the voting service.
Also some improvements for the voting service so that the service accesses the database less.
- Improve voting service
- Add voting service unit tests
- Add voting service integration tests

feat: Add integration tests for voting service

---

server/src/columns/service_integration_test.go
server/src/columns/service_test.go

Add integration tests for the column service. Also add some more unit tests for the delete method.
- Add unit tests for delete
- Add integration tests

feat: Add integration tests for column service

---

server/src/boards/database_test.go
server/src/boards/service_integration_test.go

Add integration tests for the board service.
- Add integration tests

feat: Add integration tests for board service

---

src/assets/flags/FR.svg
src/components/SettingsDialog/Appearance/__tests__/__snapshots__/Appearance.test.tsx.snap
src/components/SettingsDialog/Components/LanguageSettingsDropdown.tsx
src/i18n/de/translation.json
src/i18n/en/translation.json
src/i18n/fr/templates.json
src/i18n/fr/translation.json
src/i18n/index.ts
src/i18nTest.ts
src/routes/Homepage/Homepage.tsx
src/types/i18next.d.ts

This pull request adds French language support to the application. It introduces French translations for both general UI and retrospective templates, updates the language selection components to include French, and ensures that French resources are loaded throughout the app.
* Added French translation files for both general UI (`translation.json`) and retrospective templates (`templates.json`) under `src/i18n/fr/`.
* Updated the i18n configuration in `src/i18n/index.ts` and `src/i18nTest.ts` to register French resources alongside English and German. [[1]](diffhunk://#diff-8a518b6807c2692686b085051a2455e70aacd2bb6e1e228c3389fdec04226417R9-R12) [[2]](diffhunk://#diff-8a518b6807c2692686b085051a2455e70aacd2bb6e1e228c3389fdec04226417R23-R26) …

feat(i18n): Add French localization and flag assets
