package.json, src/components/UserList/UserList.tsx, yarn.lock
Fixes #43 
* First tap is opening the tooltip containing the own user name
* Second tap is the "ready" click
Disabling the tooltip will fix this issue
=> Disable tooltip for own user name

src/components/Modal/variant/MembershipRequestModal.tsx
gender neutral permission dialog
=> Remove `him` from requestMembership dialog

src/components/Column/Column.container.ts, src/components/Column/Column.tsx, src/components/ColumnView/ColumnView.tsx, src/components/Modal/variant/SettingsModal.tsx, src/routes/Board/Board.container.tsx, src/routes/Board/Board.spec.tsx, src/routes/Board/Board.tsx, src/routes/NewBoard/NewBoard.container.tsx, src/types/index.ts
In der Implementierung werden die Karten im Browser gefiltert und versteckt, also kann man sie mit genug "krimineller Energie" in den Sources auslesen :D Wenn das nicht reicht, überlege ich mir eine Datenbank-Query, weiß aber nicht wie umständlich es wird, da wir den `readFileSync` benutzen 🤔
=> Cards visibility

LICENSE, README.md, package.json, server/package.json
Changed license to MIT with Commons Clause, which basically means that whoever may do whatever he wants with the source code except for selling it.
=> License change: MIT with Commons Clause

src/components/MenuBars/MenuBars.tsx, src/components/MenuBars/MenuItem/MenuButton.tsx, src/components/MenuBars/MenuItem/MenuItem.scss, src/components/MenuBars/MenuItem/MenuToggle.tsx, src/components/MenuBars/__snapshots__/MenuBars.test.tsx.snap
Since we are not going to implement (maybe?) the functionality of all buttons for our upcoming release of the MVP, I thought it's a good idea to disable the buttons which haven't been implemented yet. 
I hope that's also going to reduce confusion which button can already be clicked and which will do nothing.
=> Disable unimplemented menu buttons

src/store/reducer/board.ts
<h2> Description </h2>
Instead of displaying the start of the voting phase (or other voting notifications) only when the voting phase started, it was displayed for every board edit event.
- Add undefined check for `action.board.voting` in `boardReducer`
=> Fix voting notification bug

src/components/BoardHeader/ParticipantsList/ParticipantsList.tsx, src/components/ToggleButton/ToggleButton.test.tsx, src/components/ToggleButton/ToggleButton.tsx
We've had the problem that the ToggleButton did not always show the correct state even tho the component recieved the updated props. The problem was that the internal state hasn't updated on prop change. One solution would have been to use the react hook 'useEffect' to update the state on changed props. But I've decided to remove the internal state completely because it isn't really necessary. The ToggleButton will always be in a form or something similar which will control the state correctly, so we do not need the ToggleButton to control the state itself. 
I've also decided to add some additional callback functions and some comments for better documentation and reusability.
=> Fix toggle button to always show the correct state

server/src/cloud/board.ts, server/src/model/init.ts, src/components/BoardHeader/HeaderMenu/HeaderMenu.tsx, src/components/BoardHeader/HeaderMenu/__snapshots__/HeaderMenu.test.tsx.snap, src/routes/Board/Board.tsx, src/store/action/__tests__/board.test.ts, src/store/reducer/board.ts, src/types/board.ts
<h2> Description </h2>
Moderators can now show or hide all other notes for all users. Users can only see their own notes.
Issue: #683 
- Filter notes in `routes/Board/Board.tsx`
- Add board table attribute `showNotesOfOtherUsers`
- Update `BoardClientModel` and `BoardServerModel`
- Add `HeaderMenu` entry to toggle notes
---
<details>
<summary>Visual Changes</summary>
</details>
=> Closes #683: Hide notes of other users

src/constants/style.scss
resolves bug mentioned in issue 792. 
Changes: changed z-index of backdrop to 9 so it's above menu bars z-index
=> Resolves #792

src/components/BoardHeader/BoardHeader.scss
<h2> Overflow ellipsis on board header</h2>
Board header title was not limited to max-width and could wrap before. I added the overflow settings and restricted the width
---
<details>
<summary>Visual Changes</summary>
</details>
=> Overflow ellipsis on board header

server/src/cloud/userOnlineStatus.ts, src/components/BoardHeader/BoardHeader.tsx, src/routes/Board/Board.tsx, src/store/middleware/board.ts
Closes #1172
- Update online status
- Allow users to be online on multiple boards
- Remove users if they reload or leave the board (logo or close the browser)
=> Closes #1172: Allow users to be online on multiple boards (listener, update leave logic)

src/components/Note/Note.scss
=> Change word break for note text

package.json, src/components/Board/Board.scss, src/components/Board/Board.tsx, yarn.lock
Bug fix for issue https://github.com/inovex/scrumlr.io/issues/1580
Adds scrolling to safari browsers. The root cause lies in the implementation of smooth scrolling behavior which FF an Chrome already did. This is already implemented in the technical preview of the new Safari. However, older Safari versions and the current one 15.4 does not support it which breaks the whole scrolling on Safari. 
I used a polyfill package with good Github reputation to fix this behavior (https://github.com/iamdustan/smoothscroll).
- Added smoothscroll and types to package.json
- Implemented polyfill in Board component
- Forced the use of the polyfill since safari 15.4 breaks the conditional application logic. See this issue for details (https://github.com/iamdustan/smoothscroll/issues/177)
- Removed …
=> Add polyfill to be scroll-compatible to safari browsers

src/assets/icon-share.svg, src/components/Board/Board.scss, src/components/Note/Note.tsx, src/components/Note/__tests__/__snapshots__/Note.test.tsx.snap, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogDeleteNoteButton.scss, src/components/NoteDialog/__tests__/__snapshots__/NoteDialog.test.tsx.snap, src/components/Votes/VoteButtons/AddVoteButton.tsx, src/components/Votes/VoteButtons/RemoveVoteButton.scss, src/components/Votes/VoteButtons/RemoveVoteButton.tsx, src/components/Votes/Votes.scss, src/components/Votes/Votes.tsx, src/components/Votes/__tests__/Votes.test.tsx, src/components/Votes/__tests__/__snapshots__/Votes.test.tsx.snap, src/components/VotingDialog/VotingDialog.tsx, src/components/VotingDialog/__tests__/__snapshots__/VotingDialog.test.tsx.snap
Some last minute changes for bugs/issues we've discovered in our meeting.
- Unify sizes of icons in board settings
- In "non-cumulative voting" the added votes are displayed next to the permanently displayed add vote button
- The add vote button has been disabled once no votes are remaining
- Enabled cumulative votes has become the default state
- Fixed horizontal column scrolling
- Fix the color of the trash icon in the note dialog to also be coloured in the column specific accent color 
- Show only unique votes on cards within a stack on detail screen
=> Various changes

src/components/BoardHeader/BoardHeader.tsx, src/components/BoardHeader/HeaderMenu/BoardSettings/BoardSettings.tsx, src/components/SettingsDialog/BoardSettings/BoardSettings.scss, src/components/SettingsDialog/BoardSettings/BoardSettings.tsx, src/constants/misc.ts, src/constants/style.scss
Placeholder was difficult to recognize and its behavior was not consistent.
Example:
Board name: "test" --> Open settings --> Change board name to "" --> Placeholder "scrumlr.io" displayed --> Close settings --> Board name still "test"...
- Changed placeholder colors, added defaults
- Hide placeholder on focus
- When input empty and focus lost: Reset board name and display placeholder
- Select all text on focus if board name not empty
- Aligned placeholder behavior for header menu
=> Change placeholder of inputs in Settings + Header menu

src/components/BoardHeader/BoardHeader.scss, src/components/BoardHeader/BoardHeader.tsx
Unnecessary settings cogwheel icon can be removed from header.
Removed settings cogwheel icon from header.
=> Remove settings cogwheel icon

src/components/Column/Column.tsx, src/components/Note/Note.tsx, src/components/NoteDialog/NoteDialog.scss, src/components/NoteDialog/NoteDialog.tsx
Added border to note dialog when presenting visible columns (fits well with #1641).
=> Visual hint for note dialogues in focused mode

src/components/Column/ColumnSettings.tsx
The column context menu hasn't closed itself on the loss of focus (if something outside the menu has been clicked).
=> Column context menu closes on loss of focus

src/components/Board/Board.tsx, src/components/Column/Column.scss, src/components/MenuBars/MenuBars.tsx, src/components/MenuBars/MenuItem/MenuItem.scss, src/components/MenuBars/MenuItem/MenuToggle.tsx, src/components/NoteDialog/NoteDialog.scss, src/constants/style.scss
- Changed the highlight color of the focus mode to `goal-green` (#70e000, inspired by Slack)
- Off-topic: Refactored the board colors `online-orange` and `warning-red` i.a. for better contrast
=> Remove/replace the grooming-green board color to avoid confusing it with the focused mode

src/components/MenuBars/MenuItem/MenuItem.scss
- ~~Removed absolute positioning from menu items~~ Changed positioning to fix alignment
- Added fixed width to fix oval settings icon on hover
Previously             |  Now
:-------------------------:|:-------------------------:
Previously             |  Now
:-------------------------:|:-------------------------:
=> Fix: Horizontal alignment of menu items

server/src/database/migrations/sql/1_initial_schema.up.sql, server/src/database/migrations/sql/2_update_board_sessions_table.down.sql, server/src/database/migrations/sql/2_update_board_sessions_table.up.sql
- Revert previous changes to the first migration script since it's illegal to edit them (blame on me)
- Add migration script to alter default value of `show_hidden_columns` in the `board_sessions` table
=> Change default value of show_hidden_columns

src/assets/icon-check.svg, src/components/Avatar/Avatar.scss, src/components/BoardUsers/BoardUser.scss, src/components/BoardUsers/UserAvatar.tsx
The ready checkmark is now animated so it is more noticeable. Also, avatars of ready users now have a green circle around them. Closes #1710 
- added draw and scale animation to ready checkmark
- added green stroke around avatar background of ready users
- animated green stroke around bg
https://user-images.githubusercontent.com/35272402/171211856-dda5c87e-2fab-46f7-aa61-9ee896f6b733.mov
=> Ready checkmark animation & avatar circle

src/components/SettingsDialog/ExportBoard/ExportBoard.scss
=> Change color of json icon for better visibility/readability

src/components/Board/Board.scss, src/components/Column/Column.scss
Closes #1725 
Change height for board and columns to 100% instead of 100vh and handle vertical overflow.
Updated 2 CSS selectors and added 1 more.
=> Fix column scroll on mobile

src/components/Request/Request.scss, src/constants/style.scss
Closes #1800
- Increase request component z-index (to be higher than info bar z-index)
- Add z-index to style constants
<details>
<summary>Screenshot (Before)</summary>
</details>
<details>
<summary>Screenshot (After)</summary>
</details>
=> Adjust request dialog z-index

src/components/DotButton/DotButton.scss, src/components/MenuBars/MenuBars.scss, src/components/MenuBars/MenuItem/MenuItem.scss, src/components/Note/__tests__/__snapshots__/Note.test.tsx.snap, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteContent.scss, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteContent.tsx, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogDeleteNoteButton.scss, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogNoteOptions.scss, src/components/NoteDialog/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogUnstackNoteButton.scss, src/components/NoteDialog/__tests__/NoteDialog.test.tsx, src/components/NoteDialog/__tests__/__snapshots__/NoteDialog.test.tsx.snap, src/components/Portal/Portal.tsx, src/components/Votes/VoteButtons/AddVoteButton.scss, src/components/Votes/VoteButtons/AddVoteButton.tsx, src/components/Votes/VoteButtons/RemoveVoteButton.scss, src/components/Votes/VoteButtons/VoteButton.scss, src/components/Votes/Votes.scss
Closes #1736, closes #1802, closes #1805
- Unify appearance of all NoteDialog buttons
- Make hover & focus styles visually distinguishable for all NoteDialog buttons
- Replace `<blockquote>` with `<textarea>`
- Add focus style to the action bar buttons
- Update tests & snapshots
=> Enhance hover & focus styles for Voting-, NoteDialog- and MenuBar- buttons

src/components/Avatar/Avatar.tsx
Somehow, our column settings dialog couldn't be opened anymore if the column contained notes. Seems like the `React.memo()` comparison function broke it somehow. But don't ask my how exactly because the primary reason the dialog closed instantly after opening it has been a mouse click outside of the settings dialog. So I don't know how `React.memo()` caused that  🤷‍♂️
=> Fix column settings

src/components/SettingsDialog/BoardSettings/BoardSettings.scss, src/components/SettingsDialog/BoardSettings/BoardSettings.tsx, src/components/SettingsDialog/BoardSettings/__tests__/__snapshots__/BoardSettings.test.tsx.snap, src/components/SettingsDialog/Components/SettingsInput.scss, src/components/SettingsDialog/Components/SettingsInput.tsx, src/components/SettingsDialog/ProfileSettings/ProfileSettings.scss, src/components/SettingsDialog/ProfileSettings/ProfileSettings.tsx
Added a new and improved input component to the settings modal.
- made the text inputs in the settings a separate component
- changed the input behavior so that text is left-aligned and the label moves above the text
- simplified the password input
before:
https://user-images.githubusercontent.com/35272402/175011554-1b0e947b-eb8a-47e1-ae25-4b8203ee04b7.mov
after:
https://user-images.githubusercontent.com/35272402/175011703-cdd22b04-9ac2-4ba0-a4ca-9264c4b1a5a8.mov
=> new input in settings

src/components/BoardUsers/BoardUsers.tsx
Fixed a bug where all avatars would display the local user's raisedHand status instead of the actual status of the users.
Before:
https://user-images.githubusercontent.com/35272402/176155589-0fc2ba6d-04ab-4c8c-86ac-2b824d051897.mov
=> fix: wrongly displayed raisedhand state

src/components/Note/Note.tsx
I've noticed that the avatars displayed in the note dialog were still bugged. The list of the stacked notes didn't include the avatar of the author. Therefore each note displayed the avatar of the stack parent. 
Before:
After:
=> Fix note dialog avatars

src/components/SettingsDialog/BoardSettings/BoardSettings.scss, src/components/SettingsDialog/BoardSettings/BoardSettings.tsx, src/components/SettingsDialog/BoardSettings/__tests__/__snapshots__/BoardSettings.test.tsx.snap, src/components/SettingsDialog/Components/SettingsInput.scss, src/components/SettingsDialog/Components/SettingsInput.tsx
Previously, toggling the visibility of the password in board settings would automatically save the new password. This has been fixed. Closes #1963. Also, the password hint behaved like a button.
- preventing SettingsInput's onBlur to fire when clicking its children
- removed hover state of password hint
=> Fix: toggle password visibility saves password

src/components/SettingsDialog/BoardSettings/__tests__/__snapshots__/BoardSettings.test.tsx.snap, src/components/SettingsDialog/Components/SettingsInput.tsx
The labels for our inputs in the board settings haven't had the proper input ids assigned which caused weird behaviour when hovering or clicking the labels inside their input. 
Before:
https://user-images.githubusercontent.com/36969812/178989771-6f7221ae-0b9a-48ad-be3e-aa8685ed86ee.mov
After:
https://user-images.githubusercontent.com/36969812/178989855-8b95a04a-170e-4de7-9900-24a08f3656eb.mov
=> Bug fix: Settings input hover behaviour

src/routes/LoginBoard/LoginBoard.scss
In dark mode on larger screens, the "or" above the line dividing the login providers with the username input had another background color than the background. This has been fixed:
before
after
=> fixed login divider background color in dark mode

src/components/BoardUsers/BoardUsers.tsx
A permanent "0" has been displayed next to the avatars. 
Before:
After:
=> Fix board users 

src/routes/NewBoard/NewBoard.scss
Template selection on mobile devices was left aligned which led to a gap on the right side. Now it's centered.
Before:
After:
=> Center template options on new board selection

src/components/SettingsDialog/ExportBoard/ExportBoard.tsx
The print view is now opened in a new tab.
- Removed the useNavigate hook (since it can not by itself open a new tab)
- Added window.open(...) as a replacement
=> Closes #2252: Opening print view in a new tab

server/src/main.go, server/src/realtime/redis.go, server/src/realtime/redis_test.go
Improvements after introducing redis in https://github.com/inovex/scrumlr.io/pull/2282:
- fix: actually use redis, when redis-address is set
- feat: allow passing credentials to the database
=> Allow passing credentials to Redis

src/components/TooltipButton/TooltipButton.tsx
tooltip buttons no longer show an 'undefined' hotkey
=> TooltipButton hotkey bug fix

src/routes/NewBoard/NewBoard.scss
When selecting a column template on a small screen, the application would always scroll to the top of the page. This has been fixed by setting the position of the radio button wrapper to `relative` so that the hidden inputs are not off-screen. Closes #2340
=> Fix selection of template causing a scroll to top

src/components/HotkeyAnchor/HotkeyAnchor.tsx, src/components/MenuBars/MenuBars.tsx, src/components/TooltipButton/TooltipButton.tsx
If the focus mode was ended using the hotkey, the return-to-focus-button would still be visible for users. Vice versa, if the focus mode was startet using the hotkey while already being in the stack view, the current card was not shared with the other users. Both bugs have been fix. Closes #2342 and #2345
=> Fix focus button bugs

src/components/SettingsDialog/SettingsDialog.scss
=> Fix SettingsDialog close button on Safari

src/components/Column/Column.tsx
I've remove the `onBlur` event handler from the column title input because the cancel button didn't properly work. If you change the title and click on the cancel button, the new title will still be saved because the onblur event has been fired.
=> Remove 'onBlur' from column title input

public/locales/de/translation.json, public/locales/en/translation.json, src/components/Column/Column.scss, src/components/NoteDialogComponents/NoteDialogNote.tsx, src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogOptions/NoteDialogNoteOptions.tsx, src/components/SettingsDialog/Components/SettingsDropdown.scss, src/routes/StackView/StackView.tsx, yarn.lock
Changed tooltip of the delete note button to show that the whole stack is deleted when the parent note of a stack is deleted. Also added the pointer cursor to the settings dropdown component and changed the wording for the label of the button that closes the column name edit input. Additionally closes #2452.
- added new tooltip text to note if it is the parent note of a stack and has other notes in its stack
- renamed prop for notes that are in a stack for better clarity
- added pointer cursor to settings dropdown component
- changed column edit buttons to be right-aligned
- changed wording of the button that closes the column name edit input from "reset name" to "abort"
https://user-images.githubusercontent.com/35272402/206160026-52b28236-09c4-4ecf-bfad-af1600989957.mov …
=> Small Improvements

src/components/Column/Column.scss, src/components/Column/Column.tsx, src/components/Column/__tests__/__snapshots__/Column.test.tsx.snap
After it is repeatedly noted that it is not quite clear whether a column is hidden or not, I've tried to make some improvements.
- Add crosshatched background to hidden columns
- Change the color from the hidden icon from grey to red
=> improvement: increase distinct look of hidden columns

.github/workflows/continuous-integration.yml, server/src/Dockerfile, server/src/go.mod
Bumping the version of GO to 1.18. This is necessary to use some latest go packages.
- go.mod file
- Docker base image (server)
- GitHub Action go version
=> Bumping Go to 1.18

server/src/database/types/account_type.go
The account type added in #2722 was missing in the `UnmarshalJSON` method. That should be fixed with this change.
=> Fix: Add missing account type to unmarshal method

src/constants/name.ts
I just realized that we don't have a mythical creature starting with the letter 'J'. Thus, I found it important to add one in order restore the balance of the letters.
- added 'Jackalope', a mythical creature from northamerican folklore
=> improvement: add jackalope to mythical names

src/components/SettingsDialog/ExportBoard/PrintView/PrintView.tsx
Some users reported that they somehow see just 2 blank pages when they open the print view. This does not happen every time and sometimes it fixes itself if the view is opened multiple times. We should analyse this.
I've tested it locally by serving the output of `yarn build`. Before the change, blank pages where shown. After my changes, it worked as expected. Trying it out with `yarn run` couldn't reproduce the bug. 
Closes #2941 
- Moved function that handles the printer popup to it's own useEffect which reruns on every boardData change
=> fix: print export shows blank pages

src/components/Requests/Requests.scss
The request component (for raised hands and join requests) temporarily displayed a scrollbar on its fly-in animation.
Closes #3050
- Change overflow
Before:
https://github.com/inovex/scrumlr.io/assets/36969812/6fc20b15-4e3f-4cad-b839-95085416f254
After:
https://github.com/inovex/scrumlr.io/assets/36969812/b834c7ba-dd85-4ce9-ab92-178fa43f887f
=> fix: requests displays temporary scrollbar on fly-in animation

src/store/reducer/board.ts
Previously, if the shared note is deleted by the moderator presenting it, the "Return to presented note" won't disappear for other participants due to the note not being removed as "shared note" from our redux store.
#Closes #3049
- Add functionality to board reducer to react on `DeletedNote` events and unset the `sharedNote` property if the not has been deleted
=> fix: unshare note if deleted

.github/workflows/continuous-integration.yml
fixes an issue when someone else than dependabot pushes into a branch and triggers the action.
In stead of targeting the use who triggered the action we now simply check for the suer who OG opened the PR
=> hotfix for dependabot prs

public/locales/de/translation.json, public/locales/en/translation.json, src/components/Timer/__tests__/__snapshots__/Timer.test.tsx.snap
The "Finish" tooltip on the VoteDisplay was misinterpreted as "I'm done" instead of ending voting for everyone. So I have a suggestion for improving the wording of the tooltips with this pull request. 
- Change the wording for the english and german tooltips for the vote display short actions
Before:
After:
=> improve: vote display tooltip wording

.github/workflows/continuous-integration.yml, server/src/Dockerfile, server/src/go.mod
Bumping Go to 1.19. This is necessary since some of our dependencies dropped support for 1.18.
Bumping the alpine image for our server container to 3.18.
Not particularly needed, but keeping it up-to-date. :)
- go.mod file
- Dockerfile 
- Base image server
- Final image server
- GitHub Action Go version
=> build: bumping go to 1.19 and alpine to 3.18

src/components/SettingsDialog/BoardSettings/BoardSettings.scss, src/components/SettingsDialog/BoardSettings/BoardSettings.tsx, src/components/SettingsDialog/BoardSettings/__tests__/__snapshots__/BoardSettings.test.tsx.snap, src/components/SettingsDialog/Components/SettingsButton.scss, src/components/SettingsDialog/Feedback/Feedback.scss
Small fixes and improvements for the settings dialog buttons
- Fix padding/overflow of hotkey notifications toggle
- Add consistent padding to settings buttons
- Increase size of settings button icons 
Before:
After:
=> fix: fix padding of hotkey notification toggle, increase settings button icon size

server/src/database/migrations/sql/8_add_reactions.up.sql
For older boards, the migration wouldn't work because setting the default value for the column `show_note_reactions` did not work as expected. This is fixed now.
- properly set default value of column `show_note_reactions` to `true`
=> fix: reaction db migration

src/components/BoardReactionMenu/BoardReactionMenu.scss
Fixes the board reaction menu getting rendered below notes, therefore obstructing the view.
- add `z-index` to `BoardReactionMenu` comp
=> fix: reaction menu appearing below notes

server/src/api/event_filter.go, server/src/services/boards/columns.go
Fixes an issue where notes are not displayed correctly when a column visibility is toggled from `hidden` to `shown` for participants.
added a sync function to the board-column-service.
=> fix: notes not shown correctly after updatedColumn event

src/components/TooltipPortal/TooltipPortal.scss
As of [v3.5.1](https://github.com/inovex/scrumlr.io/releases/tag/v3.5.1), a bug has emerged where reaction tooltips wouldn't disappear. This has been fixed.
- Removed `opacity` style from `TooltipPortal.scss` (=> see https://github.com/ReactTooltip/react-tooltip/issues/1112)
=> hotfix: tooltip not disappearing

src/components/Column/Column.tsx, src/components/Note/Note.tsx, src/components/Note/NoteAuthorList/NoteAuthorList.tsx, src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteHeader.tsx, src/store/middleware/board.tsx
Fixes two bugs:
- When attempting to view a note in stack view as a participant (not owner/moderator) while the option to display the note authors is disabled, the app crashes (as described in #3583). This has been fixed by not attempting to render the note author list anymore when this board setting is disabled
- When changing a board setting that affects the notes while no note is present on the board, a runtime error is produced. This has been fixed by passing `null` to the redux dispatch when no notes exist
Closes #3583
=> Fix: Two hotfixes

src/components/ConfirmationDialog/ConfirmationDialog.scss, src/components/ConfirmationDialog/ConfirmationDialog.tsx, src/components/ConfirmationDialog/__tests__/__snapshots__/ConfirmationDialog.test.tsx.snap
- concerning issue: [#3616 Switch buttons in the pop-up](https://github.com/inovex/scrumlr.io/issues/3616)
- swapped approval and cancel button
- added more spacing between the buttons
- changed order of html button elements in ConfirmationDialog component
- changed the confirmation-dialog__buttons scss class to use the default margin as gap
before: 
after:
=> style: switch button in pop up

src/components/MenuBars/MenuBars.scss
- concerning issue: Actions Bars should be closer to the border [#3723](https://github.com/inovex/scrumlr.io/issues/3723)
- moved Actionbars / Menubars further to the left and right border to slightly overlap the colored border and create an additional visual layer
- reduced left (and accordingly right) property for horizontal positioning in MenuBars.scss classes .user-menu and .admin-menu from 12px to 10px
before:
after:
=> style: move action bars closer to border

src/components/Board/Board.scss, src/components/Board/Board.tsx
- #3720
- The presenter mode no longer affects the stripe background of the spacer
- instead of changing the whole theme color of the spacer, only update the border color
- added a new styles for `.board__spacer--moderation-isActive` to change the border color to green
- removed changing the accent color to green, instead apply the `.board__spacer--moderation-isActive` class conditionally
updated, correct colors
=> fix: only apply lime color to the spacer border in presenter mode

public/locales/de/translation.json, public/locales/en/translation.json
Change the german wording of the tooltip for the short action to conclude a voting from "Abstimmung beenden" to "Abstimmung abschließen". Another AC of the issue has been to remove the abort voting short action. Since the short action has already been removed in #3840, I've only removed the translations.
Closes #3743 
- Changed the german wording of the tooltip for the short action to conclude a voting
- Removed the translation strings of the tooltip for the short action to abort a voting
=> localization: change wording of voting pill tooltip

src/components/Note/Note.scss, src/components/NoteDialogComponents/NoteDialogNote.scss
Prevent gif overflow and add rounded corners for the board view.
Closes #3846.
`min-height` and `min-width` properties are set to 100%.
This may be set to 0 instead, but was set to 100% to ensure the content grid area always uses the whole space.
More info can be found here: https://stackoverflow.com/questions/43311943/prevent-content-from-expanding-grid-items
Focus is still working as intended:
Meow meow
Instead of this:
It looks like this:
=> fix: prevent gif overflow

src/components/Column/Column.tsx
When editing the name of a column, the change should be saved when clicking anywhere outside of the input, not just the confirm button. This has been fixed. Closes #2963 
- Added onBlur event to column header input to automatically save the name change when clicking outside the input
- Added ref to close button to prevent saving the name when clicking it
=> improvement: Save new column name automatically on blur

src/components/Timer/Timer.scss, src/components/Votes/VoteDisplay/VoteDisplay.scss
Two warnings were displayed when the frontend was started. They were about the mixed support of the end value, and that it sould be replaced with flex-end. 
- Replaced end with flex-end in two components
=> style: remove postcss autoprefixer warnings by replacing `end` with `flex-end` for two components

src/components/Timer/Timer.scss, src/components/Votes/VoteDisplay/VoteDisplay.scss
With a recent change, the timer and voting icons have been replaced with our new ones. Since the new icons have a height and width of 32px, they have been distorted in the pill because their width has been set to 100% which is 38px. 
- Set the width and height of the icons in the timer and voting pill
=> fix: distorted icons in timer and voting pills

src/components/Dialog/__tests__/Dialog.test.tsx, src/components/Dialog/__tests__/__snapshots__/Dialog.test.tsx.snap, src/components/RejectionPage/RejectionPage.test.tsx, src/components/RejectionPage/__snapshots__/RejectionPage.test.tsx.snap, src/routes/NotFound/NotFound.test.tsx, src/routes/NotFound/__snapshots__/NotFound.test.tsx.snap
Some tests complained that an i18next instance had to be passed. This was quickly resolved by using our custom render method from our test utils, which wraps the component to be rendered with an i18n provider. A nice side effect is that the snapshots now show the English translations instead of the i18n keys.
=> tests: fix some tests by wrapping the rendered components in an i18n provider 

src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteContent.scss
I've had the issue that there has been a ugly scrollbar displayed in the textarea of the notes in the stack view. The reason for that is probably that Firefox handeled the `overflow-y: scroll;` differently than other browsers, because for example Chrome didn't show the scrollbar for me. 
- Change value of the overflow-y property from scroll to aut
Before:
After:
=> fix: scrollbar appearance in textarea of stackview using firefox

src/components/Column/__tests__/__snapshots__/Column.test.tsx.snap, src/components/Votes/VoteButtons/AddVoteButton.tsx, src/components/Votes/VoteButtons/RemoveVoteButton.tsx, src/components/Votes/Votes.tsx, src/components/Votes/__tests__/__snapshots__/Votes.test.tsx.snap, src/i18n/de/translation.json, src/i18n/en/translation.json
I've noticed that my accessibility tool has complained that the add- and remove-vote buttons are missing a label. Therefore I've added the translated labels as title to the dot buttons.
- Add missing translated labels
- Refactor remove vote button to retrieve number of votes via props instead of children
- Update snapshots
=> fix: add missing title to voting buttons 

src/components/Note/Note.scss
Closes #3982 
Resolves #3981 
Since the box shadow of our notes is pretty strong (in my opinion), I'm making the shadow more sublte (as discussed)
- Make note box shadow more subtle
Before:
After:
=> refactor: make note shadow more subtle

server/src/api/router.go
There has been a bug where the server returned `403 Forbidden` with the error `user board session not found` when a user tried to join a public board the first time. 
- Use the `BoardParticipantContext` for every board route individually instead of the whole group
=> fix: asking for passphrase when joining a public board

src/components/BoardReactionMenu/BoardReactionMenu.scss
I've had the strange but that scrollbars and layout shifts appeared on open/close of the board reaction menu. 
- Change the positioning of the board reaction menu from absolute to fixed.
https://github.com/inovex/scrumlr.io/assets/36969812/46f5e9d4-bd9a-438b-91d7-772289ec2a88
=> fix: board reaction open/close animation

src/components/BoardReactionContainer/BoardReactionContainer.scss
Spamming many board reactions would lead to them being displayed below the board, creating a scrollbar.
This has been fixed. Closes #4082.
- `BoardReactionMenu`: Change container position to from `absolute` to `fixed`
I used the following code to test this locally:
```ts
useEffect(() => {
setInterval(() => dispatch(Actions.addBoardReaction("heart")), 25);
}, []);
```
=> fix: board reaction spam leading to misplacement

src/components/Board/Board.tsx, src/i18n/de/translation.json, src/i18n/en/translation.json, src/routes/Board/Board.tsx
Notifies joining users if the board is currently locked.
Closes #4081. 
- get locked prop from state
- send toast if true
- add localization
is there a more sensible location for the code? i just put it somewhere because we don't really have a defined way to handle this
=> improvement: locked board notification

src/components/Note/Note.scss, src/components/Note/NoteAuthorList/NoteAuthorList.scss
The author name on a note has been cut off after a certain width even tho there was some available space.
Fixes #4128 
- Removed max width
- Decrease gap to have more space for the name
- Only apply gap if there's at least one additional author in a stack
Before:
After:
=> fix: note author name being cut off even tho theres available space

server/src/api/router.go
this allows participants to use board reactions even if the board is locked again (this was added with 540138d093bfafd34561124fed70b5d1f764ed44).  
reason being that users should still be able to do that, as it doesn't impact the state of the board itself.
- removed `BoardEditableContext` from route `initBoardReactionResources`
=> revert: reallow locked board reactions

server/src/api/context.go, server/src/api/notes_test.go, server/src/common/dto/boards.go, server/src/database/boards.go, server/src/database/boards_test.go, server/src/database/migrations/sql/15_rename_lock_board_column.down.sql, server/src/database/migrations/sql/15_rename_lock_board_column.up.sql, server/src/services/boards/boards.go, src/components/BoardHeader/HeaderMenu/BoardOptions/LockBoard.tsx, src/components/BoardHeader/HeaderMenu/__tests__/HeaderMenu.test.tsx, src/components/BoardHeader/HeaderMenu/__tests__/__snapshots__/HeaderMenu.test.tsx.snap, src/components/Note/Note.tsx, src/components/Note/NoteReactionList/NoteReactionChip/NoteReactionChip.tsx, src/components/Note/NoteReactionList/NoteReactionList.tsx, src/components/NoteDialogComponents/NoteDialogNote.tsx, src/components/NoteDialogComponents/NoteDialogNoteComponents/NoteDialogNoteContent.tsx, src/components/NoteInput/NoteInput.tsx, src/components/NoteInput/__tests__/NoteInput.test.tsx, src/components/SettingsDialog/BoardSettings/BoardSettings.tsx, src/components/SettingsDialog/BoardSettings/__tests__/__snapshots__/BoardSettings.test.tsx.snap, src/components/Votes/Votes.tsx, src/components/Votes/__tests__/Votes.test.tsx, src/i18n/de/translation.json, src/i18n/en/translation.json, src/routes/Board/Board.tsx, src/store/middleware/board.tsx, src/types/board.ts, src/utils/test/getTestApplicationState.ts
This would refactor both front -and backend so that `AllowEditing` is renamed to `IsLocked`.  
Reason: The usage before was to invert `AllowEditing` in the frontend to `isLocked`, since it is only used as such. So I thought why not rename the whole thing? See https://github.com/inovex/scrumlr.io/pull/3955#discussion_r1576251319.
- `dto/boards`
- refactor `AllowEditing` to `IsLocked`
- `database/boards`
- refactor `AllowEditing` to `IsLocked`
- change to new name everywhere else
- add migration to alter column `allow_editing` to `is_locked`
- `types/board`
- refactor `allowEditing` to `isLocked`
- refactor everywhere else this is used
- remove boolean inversion when using `appSelector`
- change localization
=> refactor: allowEditing -> isLocked

server/src/api/event_filter.go, server/src/common/dto/board_sessions.go, server/src/database/board_sessions.go, server/src/services/boards/sessions.go
Whenever someone gets promoted to moderator, he/she should be able to see the hidden columns. This is now possible since we sync columns (`ColumnsUpdated`) on a `ParticipantUpdated` event. 
Before, this call was not present resulting in a situation where the newly named moderator needed to refresh the page to finally see the hidden columns.
Since #4179 has broadened the scope of a BoardSession DTO – specifically the AccountType – I needed to extend our DB calls, since when I parse the event in the EventFilter, it errors, since AccountType can not be an empty string (at least for now).
Therefore we should check and decide, if we want to publish the AccountType information or not. If not, I can also just annotate the AccountType in the DTO with "omitempty".
- added the accounttype to our db …
=> fix: hidden columns not showing after promotion to moderator

.github/workflows/continuous-integration.yml, server/docker-compose.yml
readds the name in docker-compose, which was removed with #4205. Thanks @BenedictHomuth for the help! 
- add `name` to `docker-compose.yml`
- adjust run command in `continuous-integration.yml`
=> chore: docker compose name

deployment/SKE/create_db_job.yaml, deployment/docker/docker-compose.yml, server/docker-compose.dev.yml, server/docker-compose.yml, server/src/database/database_test.go
Since our deployment will switch to postgres 16.3 shortly, this is also now reflected in our dev env.
- Added the new version to our docker-compose files
- Added the new version to our test container in Go tests
=> build: bump postgres to 16.3

src/components/Html/Html.tsx, src/components/SettingsDialog/Components/ThemeSettings.tsx, src/constants/storage.ts, src/store/action/view.ts, src/store/middleware/view.tsx, src/store/reducer/view.ts, src/types/view.ts, src/utils/hooks/useAutoTheme.ts, src/utils/test/getTestApplicationState.ts
Changes the logic how setting of the theme is handled.
Previously, the logic was split weirdly by using the local storage directly to set/get the theme.  
Also, the Html component would hold the logic to determine what the system theme preference is.
Now, `theme` ist also part of the application store and can be set/retrieved as such with Actions etc.  
The theme is is also still saved to the local storage and retrieved initially, but the local storage key name has been streamlined with the scrumlr prefix to fit with the others.
Additionally, a hook is now used to determine the theme which is set as a global attribute.
- Add `theme` to the application store (as part of view), including Actions, Reducer, and Middleware.
- The middleware will now handle setting the local storage implicitly …
=> refactor: theme state

src/components/Column/ColumnSettings.tsx, src/routes/NewBoard/columnTemplates.ts
Quick fix:
1. Templates _Positive / Negative_ and _Plus / Delta_ had the wrong color for the second column.
2. The color selection order for columns was wrong
- Adjust template colors for the two above mentioned templates
- Adjust Column color order
=> fix: colors

server/src/database/testdata/fixture.yml
Cleanup of old observer fixture data for database tests
- removed all entries used by old observer tests in `fixture.yml`
=> chore: removed old observer fixture data

server/src/Dockerfile
Based on <https://docs.docker.com/build/guide/multi-platform/#platform-build-arguments>
you can use variables like `TARGETARCH` or `TARGETOS` to determine the architecture used in the build command
inside the Dockerfile. This would allow multiarch binary builds for the server.
relates #4339
relates #3994
Signed-off-by: Tim Beermann <tibeer@outlook.de>
The current multi-arch builds only build the container image for the desired architecture, the go binary inside is still build with the wrong architecture. This PR tries to automatically adopt the build arguments to the related architecture given in the build command.
Changed the server Dockerfile to allow platform agnostic build arguments. E.g. arm64 when docker buildx is running for platform linux/arm64.
=> Allow flexible architecture on containerbuilds depending on the build platform.

server/src/database/board_templates_test.go, server/src/database/column_templates.go, server/src/database/column_templates_test.go, server/src/database/database_test.go, server/src/database/testdata/fixture.yml
Added tests for our board and column templates.
Also fixed a typo which prevented to insert a column template under certain conditions
- extended fixture data & registered board and column templates in bun for tests
- added board template tests
- added column template tests
=> test: add go tests for board- and column-templates

src/components/MenuBars/MenuBars.tsx, src/components/MenuBars/__tests__/MenuBars.test.tsx, src/components/MenuBars/__tests__/__snapshots__/MenuBars.test.tsx.snap, src/components/TooltipButton/TooltipButton.scss, src/utils/hooks/useTimerLeft.ts
- Implemented the enhanced feedback behaviour for the "Mark me as Done" tooltip, as stated in [#4269](https://github.com/inovex/scrumlr.io/issues/4269).
- The cases are handled as follows (or at least this was the intention):
• **Voting is active / No timer** → Showing the open tooltip after 2 seconds and leaving it open until the user clicks. Clicking logs the toggle interaction. If a user decides to unmark them, the feedback shall not be shown. 
• **Voting is active / timer is active / votes are used up **before** the timer ends** → Showing the tooltip after 2 seconds and leaving it open a) until the user clicks or b) until 30 seconds after the timer expires and the user is set to ready automatically 
• **Voting not active / Timer is active** → After timer expires and the user is not …
=> feat(menu-bar): Enhanced visual feedback for "Mark me as done"

src/components/MenuBars/MenuBars.scss, src/components/SettingsDialog/BoardSettings/BoardSettings.scss, src/components/SettingsDialog/ProfileSettings/ProfileSettings.scss, src/constants/colors.scss
Recently, the following warnings came up:
```
<w> 
<w> src/constants/colors.scss 235:11                                             set-base-colors()
<w> src/constants/colors.scss 255:3                                              @import
<w> src/constants/style.scss 4:9                                                 @import
<w> src/components/BoardHeader/HeaderMenu/BoardOptions/BoardOptionLink.scss 1:9  root stylesheet
<w> 
<w> You probably don't mean to use the color value gray in interpolation here.
<w> It may end up represented as gray, which will likely produce invalid CSS.
<w> Always quote color names when using them as strings or map keys (for example, "gray").
<w> If you really want to use the color value here, use '"" + $color-name'.
```
So I did as suggested and put the map …
=> fix: scss warnings

src/components/ColorPicker/ColorPicker.scss, src/components/Column/Column.scss, src/components/Column/ColumnSettings.scss, src/constants/style.scss
Right now, the color picker isn't correctly rendered in Chrome.  
Reason for this is a wrong z-index for column header, which would lead to these problems.
The z-index was introduced in #4391, fixing another issue concerning the emoji overlay.
However, the value itself was less than the notes z-index.
The proposed changes here adjust the z-index of column headers to always be greater than the notes z-index, so all components are explicitly overlayed.
Resolves #4538.
- Added new z-index var `$column-header-z-index` which is greater than `$note-z-index`
- Applied  `$column-header-z-index` to column header
- Change z-indices in components related to the color picker; if not required removed entirely
=> fix: column header overlay

src/components/ColorPicker/ColorPicker.scss, src/components/ColorPicker/ColorPicker.tsx, src/components/Column/Column.tsx, src/components/Column/ColumnSettings.tsx, src/components/MiniMenu/MiniMenu.tsx
This PR refactors and improves on some issues with the current `ColumnSettings` and `ColorPicker` components, in order to make it usable within other components.
Previously, `ColorPicker` would dispatch the function to change the column color itself.
Since in other implementations, other things should happen upon selection, this has been moved to the parent component; a function with the selected color is propagated.
Since the ColorPicker had no state whether it was open or closed, the closed version would be rendered in the parent component.
This lead to CSS classes being mixed.
Now, also the closed color picker is rendered within the color picker itself, so no CSS has to be imported by the parent component
While we're at it, some other changes were made in an attempt to improve …
=> refactor: column settings / color picker

src/components/SettingsDialog/Components/AvatarSettings.tsx, src/components/SettingsDialog/ProfileSettings/ProfileSettings.tsx, src/components/SettingsDialog/SettingsDialog.tsx, src/store/features/auth/actions.ts, src/store/features/auth/reducer.ts, src/store/features/participants/thunks.ts
With the introduction of the newly refactored settings dialog (#4265), it was made possible to add settings screens outside a board. 
However, using this in other views, like the WIP template view (#4254) revealed that changing the user name or avatar would not be applied to the state until reloading the page.  
The reason for this is simple: We use the features `participants` and `auth` separately, both of which contain information about the name and avatar of a user. The difference lies in where the information is available: 
- `auth.user` is always available after the user has logged in
- `participants.self` is only available after joining a board.
The way these two change is also different:
- `auth.user` is initially retrieved after logging in and doesn't change.
- `participant.self` …
=> fix: local user setting change

src/components/SettingsDialog/Appearance/__tests__/Appearance.test.tsx, src/components/SettingsDialog/Appearance/__tests__/__snapshots__/Appearance.test.tsx.snap
In the months of December and January, snowfall is rendered including a setting in the `Appearance` component.
An accompanying test would compare the rendered component to a snapshot. However, since the test is reliant on time, the test will fail if the time's not right. Additionally, CI/CD runners don't necessarily synchronize their time with the real world, leading to more confusion. Hence, these tests mock the system time in order to achieve consistent results.
- `Appearance.test.tsx`
- set mocked system time
- add test to test both with and without snowfall
- `Appearance.test.tsx.snap`: update snapshot
=> test: mock system time for snowfall

src/i18n/de/translation.json, src/i18n/en/translation.json, src/routes/Homepage/Homepage.tsx
Sets the year displayed in the homepage footer to the current year. Note this PR does not apply to the Landingpage used on scrumlr.io, ~~for that see the linked PR~~
- set copyright year to dynamic current year (2021 - `{{currentYear}}`)
=> chore: update homepage copyright year

docs/src/content/docs/self-hosting/env-vars.md
I found a small typo in the example environment variables in the documentation. 
The data source name [expected here](https://bun.uptrace.dev/postgres/#supported-drivers) should start with `postgres://` and not with `psql://`. 
* Fix docs: `SCRUMLR_SERVER_DATABASE_URL`: `psql://` -> `postgres://`
=> docs: fix DSN for `SCRUMLR_SERVER_DATABASE_URL`

src/routes/Router.tsx
Users were able to go to the legacy template view (if enabled in env) without being logged in. This caused an error when trying to create a new board.
- `Router.tsx`->`/new` route element: Wrap `LegacyNewBoard` with `RequireAuthentication`
=> fix: require auth on legacy new board

src/components/NoteDialogComponents/NoteDialogNoteWrapper.scss
Stacked cards in desktop view had a slight offset. This is now fixed.
Fixes #4922
- `NoteDialogNoteWrapper`: Remove overhanging offset
=> fix: stack cards offset

src/components/Templates/CreateTemplateCard/CreateTemplateCard.scss, src/components/Templates/TemplateCard/TemplateCard.scss
decreased template card title and creation button text to 20px 
decreased template card title and creation button text to 20px
=> decreased template card title and creation button text to 20px #5184

src/components/Templates/TemplateCard/TemplateCard.tsx
Fixed wron column names in the card overview for recommended templates
added translation for recommended template columns
=> fix: added translation for recommended template columns

src/components/MenuBars/MenuBars.tsx
Fixes #4846 
Previously, one condition for the "mark as done"-pill to appear was whenever a user is not ready and a timer is finished (but still active).
this lead to the scenario where when a moderator reset the ready status of users, the pill would reappear right away (as described in #4846).
Also, one other likely redundancy in the logic was removed.
These other conditions still cause the pill to appear:
- timer expired during an active voting
- all votes are used up during an active voting
this PR changes the pill logic tp no longer show with just the timer expiring.
1. initial:
```ts
(timerExpired || USED_VOTES) && USER_NOT_READY && (state.activeTimer || state.activeVoting)
```
2. expanded (same logic):
```ts
USER_NOT_READY &&
(
(timerExpired && state.activeTimer)  ||   // timer …
```
=> fix: mark as done pill logic

server/config_example.toml, server/coverage.txt, server/src/api/board_templates_test.go, server/src/api/context.go, server/src/api/context_test.go, server/src/api/router.go
Hint! This changes are based on this [PR](https://github.com/inovex/scrumlr.io/pull/5333) so please review just following three commits:
- [fix: issue](https://github.com/inovex/scrumlr.io/commit/f6ecc39b8dbc967937c6e161f72bf7f554f32aab) 
- [fix: issue](https://github.com/inovex/scrumlr.io/commit/04f2fa4547c81e8e06f59669944945f908a67c93) 
- [fix: added missing config flags to config_example.toml](https://github.com/inovex/scrumlr.io/commit/751a909994fa08dd56985c7a1a83944887e947d9)
This PR addresses issue #5335 by implementing middleware to prevent anonymous users
from creating custom templates when the feature is disabled via configuration. The
changes include proper permission checks, comprehensive test coverage, and updated
configuration examples.
- Added new middleware …
=> fix: prevent anonymous users from creating custom templates when disabled

src/components/Column/ColumnDetails/ColumnDetails.scss, src/components/Column/ColumnDetails/ColumnDetails.tsx, src/components/Column/ColumnDetails/__tests__/__snapshots__/ColumnDetails.test.tsx.snap, src/components/Column/ColumnHeader/__tests__/__snapshots__/ColumnHeader.test.tsx.snap, src/components/Column/__tests__/__snapshots__/Column.test.tsx.snap
Improved the column spacing behavior to create better visual consistency across the board. Previously, columns without descriptions would have reduced spacing, which could make the layout look uneven when some columns had descriptions and others didn't. Now, if any column on the board has a description, all columns maintain the same height to keep everything aligned. Only when no columns have descriptions at all does the layout use compact spacing to reduce unnecessary gaps. (Issue: https://github.com/inovex/scrumlr.io/issues/5363)
Added
- New Redux selector anyColumnHasDescription to check if any column on the board has a description
- CSS modifier class --empty that removes min-height when no descriptions are present board-wide
- Comprehensive documentation comment explaining the …
=> feat: add consistent column height spacing based on board content

.github/workflows/continuous-integration.yml
This change removes the Octomind end-to-end testing integration from the CI/CD pipeline to streamline the workflow and reduce external dependencies. Cypress tests continue to provide comprehensive end-to-end testing coverage for the application. Issue: https://github.com/inovex/scrumlr.io/issues/5264
**After merging, we should clean up the env variables AUTOMAGICALLY_TOKEN & AUTOMAGICALLY_TEST_TARGET_ID**
Removed Octomind automated testing integration from the continuous integration workflow. The pipeline now relies on Cypress for end-to-end testing while maintaining comprehensive test coverage and faster build times.
=> ci: remove Octomind end-to-end testing integration

src/routes/Boards/Boards.scss
This change fixes excessive spacing between the page title and search bar on mobile devices by reducing the grid gap from 57px to 20px. The mobile template page layout now provides better space utilization and improved visual hierarchy.
fix for Issue https://github.com/inovex/scrumlr.io/issues/5395
- Mobile Template Page: Reduced spacing between title "Choose a template" and search bar from excessive whitespace to 20px for better mobile UX
- Grid Layout: Optimized CSS grid template areas and rows to eliminate unnecessary empty grid spaces on smartphone breakpoints
=> fix(ui): reduce spacing between title and search bar on mobile

src/i18n/de/translation.json, src/i18n/en/translation.json
Localization related to https://github.com/inovex/scrumlr.io/pull/5333 would only mention two hard-coded providers, whereas others might be available.
So, instead of mentioning these specifically I opted for a text which generalizes these as "login providers".
Localization key `TemplateCard.signInToCreateBoards`: Value string generalization using "login providers"
=> localization: signInToCreateBoards

server/src/boards/service.go, server/src/boards/service_test.go
Fixed missing board deletion event broadcasting in the board service to ensure connected clients receive real-time notifications when boards are deleted.
fix for https://github.com/inovex/scrumlr.io/issues/5492
Fixed
- Board deletion service now properly broadcasts BOARD_DELETED events to connected clients
- Improved error handling in board deletion to prevent partial state issues
Added
- Comprehensive test coverage for board deletion event broadcasting
- Mock expectations validation for real-time event publishing in tests
clients will be redirected to the homepage and receive a message "The board was deleted..." instead of just receiving an error:
=> fix: board deleted event is not sent to board members
